// Core JSON-schema types for the dynamic form engine.
// A Form is NEVER stored as HTML — only as this schema.

export type FieldCategory =
  | "basic"
  | "selection"
  | "upload"
  | "display"
  | "layout"
  | "action"
  | "healthcare";

export type FieldType =
  // basic
  | "text"
  | "textarea"
  | "number"
  | "email"
  | "password"
  | "phone"
  | "date"
  | "time"
  | "datetime"
  | "hidden"
  // selection
  | "radio"
  | "checkbox"
  | "dropdown"
  | "multiselect"
  | "toggle"
  | "yesno"
  | "rating"
  | "slider"
  // upload
  | "file"
  | "image"
  | "signature"
  | "medicalImage"
  // display
  | "heading"
  | "paragraph"
  | "label"
  | "divider"
  | "htmlBlock"
  | "imageDisplay"
  // layout
  | "section"
  | "card"
  | "accordion"
  | "tabs"
  | "row"
  | "column"
  | "spacer"
  // action
  | "submit"
  | "reset"
  | "cancel"
  | "previous"
  | "next"
  // healthcare
  | "patientInfo"
  | "encounterDetails"
  | "vitals"
  | "allergies"
  | "medications"
  | "diagnosisIcd10"
  | "labOrders"
  | "prescription"
  | "nursingNotes"
  | "consent"
  | "doctorSignature"
  | "patientSignature";

export type DefaultValueSource =
  | "static"
  | "currentDate"
  | "loggedInUser"
  | "patientData"
  | "databaseLookup"
  | "autoGenerated";

export interface ValidationConfig {
  required?: boolean;
  readOnly?: boolean;
  hidden?: boolean;
  disabled?: boolean;
  minLength?: number;
  maxLength?: number;
  min?: number;
  max?: number;
  pattern?: string;
  customMessage?: string;
}

export interface DisplayConfig {
  width?: "full" | "half" | "third" | "quarter";
  fontSize?: "sm" | "base" | "lg" | "xl";
  align?: "left" | "center" | "right";
  borderRadius?: "none" | "sm" | "md" | "lg" | "full";
  className?: string;
  colorAccent?: "teal" | "sage" | "brick" | "amber" | "none";
}

export interface DefaultValueConfig {
  source: DefaultValueSource;
  value?: unknown;
  lookupTable?: string;
  lookupField?: string;
}

// A single condition, e.g. { field: "gender", operator: "equals", value: "female" }
export interface ConditionRule {
  id: string;
  field: string; // internal name of the field being tested
  operator:
    | "equals"
    | "notEquals"
    | "contains"
    | "greaterThan"
    | "lessThan"
    | "greaterOrEqual"
    | "lessOrEqual"
    | "isEmpty"
    | "isNotEmpty";
  value?: unknown;
}

export type ConditionCombinator = "AND" | "OR";

export interface ConditionGroup {
  id: string;
  combinator: ConditionCombinator;
  rules: (ConditionRule | ConditionGroup)[];
}

export type ConditionAction =
  | "show"
  | "hide"
  | "enable"
  | "disable"
  | "require"
  | "unrequire"
  | "setValue"
  | "jumpToSection";

export interface ConditionalRule {
  id: string;
  name?: string;
  when: ConditionGroup;
  action: ConditionAction;
  targetFieldIds: string[]; // component ids this rule applies to
  setValueTo?: unknown; // used when action === "setValue"
  jumpTargetSectionId?: string; // used when action === "jumpToSection"
}

export interface OptionItem {
  label: string;
  value: string;
}

export interface FormComponentNode {
  id: string;
  type: FieldType;
  label?: string;
  internalName: string; // key used in submission data / conditional logic
  placeholder?: string;
  helpText?: string;
  description?: string;
  tooltip?: string;
  options?: OptionItem[]; // for radio/checkbox/dropdown/multiselect
  orientation?: "horizontal" | "vertical";
  validation: ValidationConfig;
  display: DisplayConfig;
  defaultValue?: DefaultValueConfig;
  children?: FormComponentNode[]; // for layout components (section/card/row/etc.)
  meta?: Record<string, unknown>; // type-specific extra config (e.g. file: maxSizeMb)
}

export interface FormSection {
  id: string;
  title: string;
  description?: string;
  components: FormComponentNode[];
}

export interface FormSchema {
  formId?: string;
  title: string;
  description?: string;
  layout: "single" | "two-column" | "three-column" | "four-column";
  sections: FormSection[];
  conditionalRules: ConditionalRule[];
  meta?: {
    category?: string;
    department?: string;
    tags?: string[];
  };
}
